application:
  max-file-size: ${LIMITSIZE:350000000}
  file-extensions: ${EXTENSIONS:mp4,mov,wmv,avi,webm,mkv}

server:
  port: ${PORT:8080}
  tomcat:
    max-http-post-size: ${application.max-file-size}
    max-swallow-size: ${application.max-file-size}

spring:
  application:
    name: fiap-7soat-tcg31-fiapx-api
  servlet:
    multipart:
      max-file-size: ${application.max-file-size}
      max-request-size: ${application.max-file-size}

aws:
  endpoint: http://s3.localhost.localstack.cloud:4566
  region: us-east-1
  key-id: ${AWS_ACCESS_KEY_ID:test}
  secret-key: ${AWS_SECRET_ACCESS_KEY:test}
  s3:
    bucket-name: fiap-7soat-tcg31-fiapx-bucket
    part-size: ${LIMITPARTSIZE:10485760}


rabbitmq:
  queue: ${RABBITMQ-QUEUE:process-video-queue}
  exchange: ${RABBITMQ-EXCHANGE:process-video-exchange}
  bindings: ${RABBITMQ-ROUTING-QUEUE:process-video-routing-queue}